models:
  - name: "TensroRT-LLM RAG Portal"
    model_path: "/Users/sergeyleksikov/Documents/GitHub/RAGModelService"
    service:
      pre_start_actions:
        - action: run_command
          args:
            command: ["/bin/bash", "/models/RAGModelService/setup_portal.sh"]
      start_command:
        - /bin/bash
        - /models/RAGModelService/start_portal.sh
      port: 8000